# -*- coding: utf-8 -*-
"""Multiagent_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3WlDz_g2R7s3VGSNyq4aG8oSG2GwN3i
"""

!pip install -q autogen langchain-core langchain-groq seaborn matplotlib pandas

import seaborn as sns
df = sns.load_dataset('titanic')
df.to_csv('titanic.csv', index=False)

import os
from autogen import AssistantAgent, UserProxyAgent
from google.colab import userdata

# Получаем API-ключ
GROQ_API_KEY = userdata.get('GROQ_API_KEY')

# Конфигурация модели
config_list = [
    {
        "model": "llama-3.1-8b-instant",
        "api_key": GROQ_API_KEY,
        "base_url": "https://api.groq.com/openai/v1",
        "api_type": "openai"
    }
]

from autogen import AssistantAgent, UserProxyAgent, GroupChat, GroupChatManager

from google.colab import userdata
GROQ_API_KEY = userdata.get('GROQ_API_KEY')

config_list = [{
    "model": "llama-3.1-8b-instant",
    "api_key": GROQ_API_KEY,
    "base_url": "https://api.groq.com/openai/v1",
    "api_type": "openai"
}]

# Ассистент
assistant = AssistantAgent(
    name="assistant",
    system_message="Ты — эксперт по Python и анализу данных. Всегда включай все необходимые импорты. В датасете titanic из seaborn колонки в нижнем регистре: 'sex', 'survived', 'age'.",
    llm_config={"config_list": config_list, "temperature": 0.5}
)

# Критик
critic = AssistantAgent(
    name="critic",
    system_message="Проверь код на наличие: 1) всех импортов, 2) правильных названий колонок ('sex', не 'Sex'), 3) корректного синтаксиса. Если есть ошибка — НЕ говори 'код корректен'.",
    llm_config={"config_list": config_list, "temperature": 0.2}
)

# UserProxy — с ограниченным числом попыток
user_proxy = UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=3,  # ← уменьшено
    code_execution_config={"work_dir": "coding", "use_docker": False}
)

# Групповой чат
groupchat = GroupChat(agents=[user_proxy, assistant, critic], messages=[], max_round=8)
manager = GroupChatManager(groupchat=groupchat, llm_config={"config_list": config_list})

# задача
task = """
Загрузи датасет с помощью: `titanic = sns.load_dataset('titanic')`.
Выполни:
1. Круговую диаграмму по колонке 'sex' (маленькая буква!).
2. Круговую диаграмму по 'survived' (0 и 1).
3. Выведи средний возраст: `titanic['age'].mean()`.
4. Построй heatmap корреляций числовых колонок.

Обязательно включи в начало кода:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt.
"""

# Запуск (подождите 1–2 минуты после ошибки 429!)
user_proxy.initiate_chat(manager, message=task)

"""Используем полученный код и посмотрим результат"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Загрузим датасет
titanic = sns.load_dataset('titanic')

# 1. Круговая диаграмма по колонке 'sex'
plt.figure(figsize=(8, 6))
sns.countplot(x='sex', data=titanic)
plt.title('Количество людей по полу')
plt.show()

# 2. Круговая диаграмма по 'survived'
plt.figure(figsize=(8, 6))
sns.countplot(x='survived', data=titanic)
plt.title('Количество выживших и погибших')
plt.show()

# 3. Выведем средний возраст
print(titanic['age'].mean())

# 4. Построим heatmap корреляций числовых колонок
numeric_cols = titanic.select_dtypes(include=['int64', 'float64']).columns
corr_matrix = titanic[numeric_cols].corr()
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', square=True)
plt.title('Heatmap корреляций')
plt.show()